// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ConceptLinkLinkType.
const (
	AppliesTo             ConceptLinkLinkType = "appliesTo"
	Enriches              ConceptLinkLinkType = "enriches"
	HasSoftPrerequisite   ConceptLinkLinkType = "hasSoftPrerequisite"
	HasStrictPrerequisite ConceptLinkLinkType = "hasStrictPrerequisite"
	IsAnalogousTo         ConceptLinkLinkType = "isAnalogousTo"
)

// Defines values for ForecastResponseDataConfidence.
const (
	High ForecastResponseDataConfidence = "high"
	Low  ForecastResponseDataConfidence = "low"
)

// Defines values for ForecastResponseStatus.
const (
	NotOnTrack ForecastResponseStatus = "not-on-track"
	OnTrack    ForecastResponseStatus = "on-track"
)

// Defines values for GapDiagnosisResponseStatus.
const (
	NoRootCauseFound GapDiagnosisResponseStatus = "no-root-cause-found"
	RootCausesFound  GapDiagnosisResponseStatus = "root-causes-found"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusDown     HealthResponseStatus = "down"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
)

// Defines values for JwksResponseKeysAlg.
const (
	RS256 JwksResponseKeysAlg = "RS256"
)

// Defines values for JwksResponseKeysKty.
const (
	RSA JwksResponseKeysKty = "RSA"
)

// Defines values for JwksResponseKeysUse.
const (
	Sig JwksResponseKeysUse = "sig"
)

// Defines values for MasteryRecordRequestStatus.
const (
	MasteryRecordRequestStatusInProgress MasteryRecordRequestStatus = "in_progress"
	MasteryRecordRequestStatusMastered   MasteryRecordRequestStatus = "mastered"
	MasteryRecordRequestStatusSkipped    MasteryRecordRequestStatus = "skipped"
)

// Defines values for ModuleProgressItemDeviationCause.
const (
	Acceleration ModuleProgressItemDeviationCause = "acceleration"
	Break        ModuleProgressItemDeviationCause = "break"
	MorePractice ModuleProgressItemDeviationCause = "more_practice"
	Unspecified  ModuleProgressItemDeviationCause = "unspecified"
	VolumeChange ModuleProgressItemDeviationCause = "volume_change"
)

// Defines values for ModuleProgressItemStatus.
const (
	ModuleProgressItemStatusInProgress ModuleProgressItemStatus = "in_progress"
	ModuleProgressItemStatusMastered   ModuleProgressItemStatus = "mastered"
	ModuleProgressItemStatusNotStarted ModuleProgressItemStatus = "not_started"
	ModuleProgressItemStatusSkipped    ModuleProgressItemStatus = "skipped"
)

// Defines values for PrioritizedDeficitPriority.
const (
	Essential          PrioritizedDeficitPriority = "essential"
	Optional           PrioritizedDeficitPriority = "optional"
	StrictPrerequisite PrioritizedDeficitPriority = "strict_prerequisite"
)

// Defines values for PrioritizedDeficitStatus.
const (
	Missing                PrioritizedDeficitStatus = "missing"
	Partial                PrioritizedDeficitStatus = "partial"
	RequiresRouteExtension PrioritizedDeficitStatus = "requires_route_extension"
)

// Defines values for ProjectIdeaResponseDifficultyLevel.
const (
	Advanced ProjectIdeaResponseDifficultyLevel = "advanced"
	Basic    ProjectIdeaResponseDifficultyLevel = "basic"
	Medium   ProjectIdeaResponseDifficultyLevel = "medium"
)

// Defines values for ReadinessResponseChecksDatabase.
const (
	ReadinessResponseChecksDatabaseDown ReadinessResponseChecksDatabase = "down"
	ReadinessResponseChecksDatabaseUp   ReadinessResponseChecksDatabase = "up"
)

// Defines values for ReadinessResponseChecksIdentityProvider.
const (
	Down ReadinessResponseChecksIdentityProvider = "down"
	Up   ReadinessResponseChecksIdentityProvider = "up"
)

// Defines values for ReadinessResponseStatus.
const (
	Degraded ReadinessResponseStatus = "degraded"
	Ok       ReadinessResponseStatus = "ok"
)

// Defines values for ResourceType.
const (
	ResourceTypeContent  ResourceType = "content"
	ResourceTypeEnabling ResourceType = "enabling"
)

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// Defines values for ListResourcesParamsType.
const (
	ListResourcesParamsTypeContent  ListResourcesParamsType = "content"
	ListResourcesParamsTypeEnabling ListResourcesParamsType = "enabling"
)

// Checkpoint defines model for Checkpoint.
type Checkpoint struct {
	Date                  time.Time `json:"date"`
	Name                  string    `json:"name"`
	TargetCoveragePercent *float32  `json:"target_coverage_percent,omitempty"`
}

// Concept defines model for Concept.
type Concept struct {
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`

	// Links Linked topics from the ontology graph.
	Links *[]ConceptLink `json:"links,omitempty"`
	Title string         `json:"title"`
}

// ConceptLink defines model for ConceptLink.
type ConceptLink struct {
	LinkType ConceptLinkLinkType `json:"link_type"`
	TopicId  string              `json:"topic_id"`
}

// ConceptLinkLinkType defines model for ConceptLink.LinkType.
type ConceptLinkLinkType string

// ConceptResponse defines model for ConceptResponse.
type ConceptResponse struct {
	Concept Concept `json:"concept"`
}

// CoverageResponse defines model for CoverageResponse.
type CoverageResponse struct {
	Covered  int        `json:"covered"`
	Deficits *[]Deficit `json:"deficits,omitempty"`
	Percent  float32    `json:"percent"`
	Ready    *bool      `json:"ready,omitempty"`
	Total    int        `json:"total"`
}

// Deficit defines model for Deficit.
type Deficit struct {
	BlockingModuleId *string `json:"blocking_module_id,omitempty"`
	RequirementId    string  `json:"requirement_id"`
}

// DeficitListResponse defines model for DeficitListResponse.
type DeficitListResponse struct {
	// Deficits Deficits sorted by priority (strict > essential > optional).
	Deficits []PrioritizedDeficit `json:"deficits"`

	// Total Total number of uncovered requirements.
	Total int `json:"total"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Endpoint Endpoint that produced the error (for 501 stubs).
	Endpoint *string `json:"endpoint,omitempty"`

	// Error Machine-readable error code.
	Error string `json:"error"`

	// Message Human-readable error detail.
	Message *string `json:"message,omitempty"`
}

// ForecastResponse defines model for ForecastResponse.
type ForecastResponse struct {
	DataConfidence   *ForecastResponseDataConfidence `json:"data_confidence,omitempty"`
	ExpectedDate     *openapi_types.Date             `json:"expected_date,omitempty"`
	KeyRisks         *[]string                       `json:"key_risks,omitempty"`
	RemainingModules *int                            `json:"remaining_modules,omitempty"`
	Status           ForecastResponseStatus          `json:"status"`

	// Velocity Modules completed per day.
	Velocity *float32 `json:"velocity,omitempty"`
}

// ForecastResponseDataConfidence defines model for ForecastResponse.DataConfidence.
type ForecastResponseDataConfidence string

// ForecastResponseStatus defines model for ForecastResponse.Status.
type ForecastResponseStatus string

// GapDiagnosisResponse defines model for GapDiagnosisResponse.
type GapDiagnosisResponse struct {
	RootCauses []RootCause                `json:"root_causes"`
	Status     GapDiagnosisResponseStatus `json:"status"`
}

// GapDiagnosisResponseStatus defines model for GapDiagnosisResponse.Status.
type GapDiagnosisResponseStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Env Deployment environment.
	Env *string `json:"env,omitempty"`

	// Status Health status of the service.
	Status HealthResponseStatus `json:"status"`

	// Uptime Process uptime (e.g. "1m30s").
	Uptime *string `json:"uptime,omitempty"`

	// Version Build version.
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus Health status of the service.
type HealthResponseStatus string

// JwksResponse defines model for JwksResponse.
type JwksResponse struct {
	// Keys JSON Web Keys (RSA public keys).
	Keys []struct {
		Alg *JwksResponseKeysAlg `json:"alg,omitempty"`

		// E RSA public exponent (base64url).
		E   *string              `json:"e,omitempty"`
		Kid *string              `json:"kid,omitempty"`
		Kty *JwksResponseKeysKty `json:"kty,omitempty"`

		// N RSA modulus (base64url).
		N   *string              `json:"n,omitempty"`
		Use *JwksResponseKeysUse `json:"use,omitempty"`
	} `json:"keys"`
}

// JwksResponseKeysAlg defines model for JwksResponse.Keys.Alg.
type JwksResponseKeysAlg string

// JwksResponseKeysKty defines model for JwksResponse.Keys.Kty.
type JwksResponseKeysKty string

// JwksResponseKeysUse defines model for JwksResponse.Keys.Use.
type JwksResponseKeysUse string

// MasteryRecordRequest defines model for MasteryRecordRequest.
type MasteryRecordRequest struct {
	ModuleId string `json:"module_id"`

	// Score Optional mastery score 0..1.
	Score  *float32                   `json:"score,omitempty"`
	Status MasteryRecordRequestStatus `json:"status"`
}

// MasteryRecordRequestStatus defines model for MasteryRecordRequest.Status.
type MasteryRecordRequestStatus string

// MasteryRecordResponse defines model for MasteryRecordResponse.
type MasteryRecordResponse struct {
	LearnerId  string     `json:"learner_id"`
	ModuleId   string     `json:"module_id"`
	RecordedAt *time.Time `json:"recorded_at,omitempty"`
	Status     string     `json:"status"`
}

// ModuleProgressItem defines model for ModuleProgressItem.
type ModuleProgressItem struct {
	ActualDate     *openapi_types.Date               `json:"actual_date,omitempty"`
	DeviationCause *ModuleProgressItemDeviationCause `json:"deviation_cause,omitempty"`
	DeviationDays  *int                              `json:"deviation_days,omitempty"`
	ModuleId       string                            `json:"module_id"`
	PlannedDate    *openapi_types.Date               `json:"planned_date,omitempty"`
	Status         ModuleProgressItemStatus          `json:"status"`
}

// ModuleProgressItemDeviationCause defines model for ModuleProgressItem.DeviationCause.
type ModuleProgressItemDeviationCause string

// ModuleProgressItemStatus defines model for ModuleProgressItem.Status.
type ModuleProgressItemStatus string

// PlanResponse defines model for PlanResponse.
type PlanResponse struct {
	Checkpoints     *[]Checkpoint `json:"checkpoints,omitempty"`
	GoalModuleId    *string       `json:"goal_module_id,omitempty"`
	LearnerId       string        `json:"learner_id"`
	OntologyVersion *string       `json:"ontology_version,omitempty"`
	PlanId          string        `json:"plan_id"`
	Status          string        `json:"status"`
	Steps           *[]PlanStep   `json:"steps,omitempty"`
	TimelineEnd     time.Time     `json:"timeline_end"`
	TimelineStart   time.Time     `json:"timeline_start"`
}

// PlanStep defines model for PlanStep.
type PlanStep struct {
	Horizon      *string    `json:"horizon,omitempty"`
	ModuleId     string     `json:"module_id"`
	PlannedEnd   *time.Time `json:"planned_end,omitempty"`
	PlannedStart *time.Time `json:"planned_start,omitempty"`
	Position     int        `json:"position"`
}

// PrioritizedDeficit defines model for PrioritizedDeficit.
type PrioritizedDeficit struct {
	EffortEstimate  *string                    `json:"effort_estimate,omitempty"`
	LinkedModuleIds *[]string                  `json:"linked_module_ids,omitempty"`
	Priority        PrioritizedDeficitPriority `json:"priority"`
	RequirementId   string                     `json:"requirement_id"`
	Status          *PrioritizedDeficitStatus  `json:"status,omitempty"`
}

// PrioritizedDeficitPriority defines model for PrioritizedDeficit.Priority.
type PrioritizedDeficitPriority string

// PrioritizedDeficitStatus defines model for PrioritizedDeficit.Status.
type PrioritizedDeficitStatus string

// ProgressResponse defines model for ProgressResponse.
type ProgressResponse struct {
	GeneratedAt *time.Time `json:"generated_at,omitempty"`
	LearnerId   string     `json:"learner_id"`

	// Modules Per-module plan-vs-actual comparison.
	Modules []ModuleProgressItem `json:"modules"`
	PlanId  *string              `json:"plan_id,omitempty"`
}

// ProjectIdeaResponse defines model for ProjectIdeaResponse.
type ProjectIdeaResponse struct {
	DifficultyLevel *ProjectIdeaResponseDifficultyLevel `json:"difficulty_level,omitempty"`
	ExpectedOutcome *string                             `json:"expected_outcome,omitempty"`
	Id              string                              `json:"id"`
	Modules         *[]string                           `json:"modules,omitempty"`
	Title           string                              `json:"title"`
}

// ProjectIdeaResponseDifficultyLevel defines model for ProjectIdeaResponse.DifficultyLevel.
type ProjectIdeaResponseDifficultyLevel string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	// Checks Per-dependency check results.
	Checks *struct {
		Database         *ReadinessResponseChecksDatabase         `json:"database,omitempty"`
		IdentityProvider *ReadinessResponseChecksIdentityProvider `json:"identity_provider,omitempty"`
	} `json:"checks,omitempty"`
	Env *string `json:"env,omitempty"`

	// Status Overall readiness.
	Status  ReadinessResponseStatus `json:"status"`
	Uptime  *string                 `json:"uptime,omitempty"`
	Version *string                 `json:"version,omitempty"`
}

// ReadinessResponseChecksDatabase defines model for ReadinessResponse.Checks.Database.
type ReadinessResponseChecksDatabase string

// ReadinessResponseChecksIdentityProvider defines model for ReadinessResponse.Checks.IdentityProvider.
type ReadinessResponseChecksIdentityProvider string

// ReadinessResponseStatus Overall readiness.
type ReadinessResponseStatus string

// Resource defines model for Resource.
type Resource struct {
	Cost            *float32     `json:"cost,omitempty"`
	Difficulty      *string      `json:"difficulty,omitempty"`
	DurationMinutes *int         `json:"duration_minutes,omitempty"`
	Format          *string      `json:"format,omitempty"`
	Id              string       `json:"id"`
	Source          *string      `json:"source,omitempty"`
	Title           *string      `json:"title,omitempty"`
	Type            ResourceType `json:"type"`
	Uri             *string      `json:"uri,omitempty"`
}

// ResourceType defines model for Resource.Type.
type ResourceType string

// ResourceListResponse defines model for ResourceListResponse.
type ResourceListResponse struct {
	Items []Resource `json:"items"`
	Total int        `json:"total"`
}

// RootCause defines model for RootCause.
type RootCause struct {
	BlockedModules *int     `json:"blocked_modules,omitempty"`
	Mastery        *float32 `json:"mastery,omitempty"`
	ModuleId       string   `json:"module_id"`
}

// RouteComputeRequest defines model for RouteComputeRequest.
type RouteComputeRequest struct {
	// GoalTopicId Goal topic (e.g. "math-5-10").
	GoalTopicId string `json:"goal_topic_id"`

	// LearnerId Learner performing the request.
	LearnerId string `json:"learner_id"`
}

// RouteComputeResponse defines model for RouteComputeResponse.
type RouteComputeResponse struct {
	Metadata *struct {
		ComputedAt  *time.Time `json:"computed_at,omitempty"`
		GoalTopicId *string    `json:"goal_topic_id,omitempty"`
		LearnerId   *string    `json:"learner_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Route Ordered list of topics forming the route.
	Route []RouterTopic `json:"route"`
}

// RouterTopic defines model for RouterTopic.
type RouterTopic struct {
	// LinkType Link type from the parent in the route (e.g. hasStrictPrerequisite).
	LinkType *string `json:"link_type,omitempty"`

	// Order Position in the route (0-based).
	Order   int    `json:"order"`
	TopicId string `json:"topic_id"`
}

// SparqlResponse defines model for SparqlResponse.
type SparqlResponse struct {
	Head struct {
		Vars *[]string `json:"vars,omitempty"`
	} `json:"head"`
	Results struct {
		Bindings *[]map[string]interface{} `json:"bindings,omitempty"`
	} `json:"results"`
}

// StoryResponse defines model for StoryResponse.
type StoryResponse struct {
	Id             string    `json:"id"`
	LinkedModules  *[]string `json:"linked_modules,omitempty"`
	ReadingMinutes *int      `json:"reading_minutes,omitempty"`

	// RealWorld Real-world application section.
	RealWorld *string   `json:"real_world,omitempty"`
	Subjects  *[]string `json:"subjects,omitempty"`
	Text      *string   `json:"text,omitempty"`
	Title     string    `json:"title"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// Roles Roles to embed (defaults to ["learner"]).
	Roles *[]string `json:"roles,omitempty"`

	// UserId Subject identifier to embed as the JWT sub claim.
	UserId string `json:"user_id"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken Signed RS256 JWT.
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds (24h).
	ExpiresIn int64                  `json:"expires_in"`
	TokenType TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Roles  []string `json:"roles"`
	UserId string   `json:"user_id"`
}

// DiagnoseGapsParams defines parameters for DiagnoseGaps.
type DiagnoseGapsParams struct {
	LagModuleId string `form:"lag_module_id" json:"lag_module_id"`
}

// GetOntologyConceptParams defines parameters for GetOntologyConcept.
type GetOntologyConceptParams struct {
	// TopicId Concept/topic identifier, e.g. "math-5-1".
	TopicId string `form:"topic_id" json:"topic_id"`
}

// ListResourcesParams defines parameters for ListResources.
type ListResourcesParams struct {
	// Type Resource kind filter.
	Type *ListResourcesParamsType `form:"type,omitempty" json:"type,omitempty"`

	// Format Resource format filter (e.g. video, text, interactive).
	Format *string `form:"format,omitempty" json:"format,omitempty"`

	// Difficulty Difficulty filter (e.g. basic, advanced).
	Difficulty *string `form:"difficulty,omitempty" json:"difficulty,omitempty"`
	Limit      *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListResourcesParamsType defines parameters for ListResources.
type ListResourcesParamsType string

// SparqlQueryParams defines parameters for SparqlQuery.
type SparqlQueryParams struct {
	// Query Read-only SPARQL SELECT query.
	Query string `form:"query" json:"query"`
}

// IssueTokenJSONRequestBody defines body for IssueToken for application/json ContentType.
type IssueTokenJSONRequestBody = TokenRequest

// RecordModuleMasteredJSONRequestBody defines body for RecordModuleMastered for application/json ContentType.
type RecordModuleMasteredJSONRequestBody = MasteryRecordRequest

// ComputeRouteJSONRequestBody defines body for ComputeRoute for application/json ContentType.
type ComputeRouteJSONRequestBody = RouteComputeRequest
