// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ConceptLinkLinkType.
const (
	AppliesTo             ConceptLinkLinkType = "appliesTo"
	Enriches              ConceptLinkLinkType = "enriches"
	HasSoftPrerequisite   ConceptLinkLinkType = "hasSoftPrerequisite"
	HasStrictPrerequisite ConceptLinkLinkType = "hasStrictPrerequisite"
	IsAnalogousTo         ConceptLinkLinkType = "isAnalogousTo"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusDown     HealthResponseStatus = "down"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
)

// Defines values for JwksResponseKeysAlg.
const (
	RS256 JwksResponseKeysAlg = "RS256"
)

// Defines values for JwksResponseKeysKty.
const (
	RSA JwksResponseKeysKty = "RSA"
)

// Defines values for JwksResponseKeysUse.
const (
	Sig JwksResponseKeysUse = "sig"
)

// Defines values for ReadinessResponseChecksDatabase.
const (
	ReadinessResponseChecksDatabaseDown ReadinessResponseChecksDatabase = "down"
	ReadinessResponseChecksDatabaseUp   ReadinessResponseChecksDatabase = "up"
)

// Defines values for ReadinessResponseChecksIdentityProvider.
const (
	Down ReadinessResponseChecksIdentityProvider = "down"
	Up   ReadinessResponseChecksIdentityProvider = "up"
)

// Defines values for ReadinessResponseStatus.
const (
	Degraded ReadinessResponseStatus = "degraded"
	Ok       ReadinessResponseStatus = "ok"
)

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// Concept defines model for Concept.
type Concept struct {
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`

	// Links Linked topics from the ontology graph.
	Links *[]ConceptLink `json:"links,omitempty"`
	Title string         `json:"title"`
}

// ConceptLink defines model for ConceptLink.
type ConceptLink struct {
	LinkType ConceptLinkLinkType `json:"link_type"`
	TopicId  string              `json:"topic_id"`
}

// ConceptLinkLinkType defines model for ConceptLink.LinkType.
type ConceptLinkLinkType string

// ConceptResponse defines model for ConceptResponse.
type ConceptResponse struct {
	Concept Concept `json:"concept"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Endpoint Endpoint that produced the error (for 501 stubs).
	Endpoint *string `json:"endpoint,omitempty"`

	// Error Machine-readable error code.
	Error string `json:"error"`

	// Message Human-readable error detail.
	Message *string `json:"message,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Env Deployment environment.
	Env *string `json:"env,omitempty"`

	// Status Health status of the service.
	Status HealthResponseStatus `json:"status"`

	// Uptime Process uptime (e.g. "1m30s").
	Uptime *string `json:"uptime,omitempty"`

	// Version Build version.
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus Health status of the service.
type HealthResponseStatus string

// JwksResponse defines model for JwksResponse.
type JwksResponse struct {
	// Keys JSON Web Keys (RSA public keys).
	Keys []struct {
		Alg *JwksResponseKeysAlg `json:"alg,omitempty"`

		// E RSA public exponent (base64url).
		E   *string              `json:"e,omitempty"`
		Kid *string              `json:"kid,omitempty"`
		Kty *JwksResponseKeysKty `json:"kty,omitempty"`

		// N RSA modulus (base64url).
		N   *string              `json:"n,omitempty"`
		Use *JwksResponseKeysUse `json:"use,omitempty"`
	} `json:"keys"`
}

// JwksResponseKeysAlg defines model for JwksResponse.Keys.Alg.
type JwksResponseKeysAlg string

// JwksResponseKeysKty defines model for JwksResponse.Keys.Kty.
type JwksResponseKeysKty string

// JwksResponseKeysUse defines model for JwksResponse.Keys.Use.
type JwksResponseKeysUse string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	// Checks Per-dependency check results.
	Checks *struct {
		Database         *ReadinessResponseChecksDatabase         `json:"database,omitempty"`
		IdentityProvider *ReadinessResponseChecksIdentityProvider `json:"identity_provider,omitempty"`
	} `json:"checks,omitempty"`
	Env *string `json:"env,omitempty"`

	// Status Overall readiness.
	Status  ReadinessResponseStatus `json:"status"`
	Uptime  *string                 `json:"uptime,omitempty"`
	Version *string                 `json:"version,omitempty"`
}

// ReadinessResponseChecksDatabase defines model for ReadinessResponse.Checks.Database.
type ReadinessResponseChecksDatabase string

// ReadinessResponseChecksIdentityProvider defines model for ReadinessResponse.Checks.IdentityProvider.
type ReadinessResponseChecksIdentityProvider string

// ReadinessResponseStatus Overall readiness.
type ReadinessResponseStatus string

// RouteComputeRequest defines model for RouteComputeRequest.
type RouteComputeRequest struct {
	// GoalTopicId Goal topic (e.g. "math-5-10").
	GoalTopicId string `json:"goal_topic_id"`

	// LearnerId Learner performing the request.
	LearnerId string `json:"learner_id"`
}

// RouteComputeResponse defines model for RouteComputeResponse.
type RouteComputeResponse struct {
	Metadata *struct {
		ComputedAt  *time.Time `json:"computed_at,omitempty"`
		GoalTopicId *string    `json:"goal_topic_id,omitempty"`
		LearnerId   *string    `json:"learner_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Route Ordered list of topics forming the route.
	Route []RouterTopic `json:"route"`
}

// RouterTopic defines model for RouterTopic.
type RouterTopic struct {
	// LinkType Link type from the parent in the route (e.g. hasStrictPrerequisite).
	LinkType *string `json:"link_type,omitempty"`

	// Order Position in the route (0-based).
	Order   int    `json:"order"`
	TopicId string `json:"topic_id"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// Roles Roles to embed (defaults to ["learner"]).
	Roles *[]string `json:"roles,omitempty"`

	// UserId Subject identifier to embed as the JWT sub claim.
	UserId string `json:"user_id"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken Signed RS256 JWT.
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds (24h).
	ExpiresIn int64                  `json:"expires_in"`
	TokenType TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Roles  []string `json:"roles"`
	UserId string   `json:"user_id"`
}

// GetOntologyConceptParams defines parameters for GetOntologyConcept.
type GetOntologyConceptParams struct {
	// TopicId Concept/topic identifier, e.g. "math-5-1".
	TopicId string `form:"topic_id" json:"topic_id"`
}

// IssueTokenJSONRequestBody defines body for IssueToken for application/json ContentType.
type IssueTokenJSONRequestBody = TokenRequest

// ComputeRouteJSONRequestBody defines body for ComputeRoute for application/json ContentType.
type ComputeRouteJSONRequestBody = RouteComputeRequest
