// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ConceptLinkLinkType.
const (
	AppliesTo             ConceptLinkLinkType = "appliesTo"
	Enriches              ConceptLinkLinkType = "enriches"
	HasSoftPrerequisite   ConceptLinkLinkType = "hasSoftPrerequisite"
	HasStrictPrerequisite ConceptLinkLinkType = "hasStrictPrerequisite"
	IsAnalogousTo         ConceptLinkLinkType = "isAnalogousTo"
)

// Defines values for GapDiagnosisResponseStatus.
const (
	NoRootCauseFound GapDiagnosisResponseStatus = "no-root-cause-found"
	RootCausesFound  GapDiagnosisResponseStatus = "root-causes-found"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusDown     HealthResponseStatus = "down"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
)

// Defines values for JwksResponseKeysAlg.
const (
	RS256 JwksResponseKeysAlg = "RS256"
)

// Defines values for JwksResponseKeysKty.
const (
	RSA JwksResponseKeysKty = "RSA"
)

// Defines values for JwksResponseKeysUse.
const (
	Sig JwksResponseKeysUse = "sig"
)

// Defines values for ReadinessResponseChecksDatabase.
const (
	ReadinessResponseChecksDatabaseDown ReadinessResponseChecksDatabase = "down"
	ReadinessResponseChecksDatabaseUp   ReadinessResponseChecksDatabase = "up"
)

// Defines values for ReadinessResponseChecksIdentityProvider.
const (
	Down ReadinessResponseChecksIdentityProvider = "down"
	Up   ReadinessResponseChecksIdentityProvider = "up"
)

// Defines values for ReadinessResponseStatus.
const (
	Degraded ReadinessResponseStatus = "degraded"
	Ok       ReadinessResponseStatus = "ok"
)

// Defines values for ResourceType.
const (
	ResourceTypeContent  ResourceType = "content"
	ResourceTypeEnabling ResourceType = "enabling"
)

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// Defines values for ListResourcesParamsType.
const (
	ListResourcesParamsTypeContent  ListResourcesParamsType = "content"
	ListResourcesParamsTypeEnabling ListResourcesParamsType = "enabling"
)

// Checkpoint defines model for Checkpoint.
type Checkpoint struct {
	Date                  time.Time `json:"date"`
	Name                  string    `json:"name"`
	TargetCoveragePercent *float32  `json:"target_coverage_percent,omitempty"`
}

// Concept defines model for Concept.
type Concept struct {
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`

	// Links Linked topics from the ontology graph.
	Links *[]ConceptLink `json:"links,omitempty"`
	Title string         `json:"title"`
}

// ConceptLink defines model for ConceptLink.
type ConceptLink struct {
	LinkType ConceptLinkLinkType `json:"link_type"`
	TopicId  string              `json:"topic_id"`
}

// ConceptLinkLinkType defines model for ConceptLink.LinkType.
type ConceptLinkLinkType string

// ConceptResponse defines model for ConceptResponse.
type ConceptResponse struct {
	Concept Concept `json:"concept"`
}

// CoverageResponse defines model for CoverageResponse.
type CoverageResponse struct {
	Covered  int        `json:"covered"`
	Deficits *[]Deficit `json:"deficits,omitempty"`
	Percent  float32    `json:"percent"`
	Ready    *bool      `json:"ready,omitempty"`
	Total    int        `json:"total"`
}

// Deficit defines model for Deficit.
type Deficit struct {
	BlockingModuleId *string `json:"blocking_module_id,omitempty"`
	RequirementId    string  `json:"requirement_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Endpoint Endpoint that produced the error (for 501 stubs).
	Endpoint *string `json:"endpoint,omitempty"`

	// Error Machine-readable error code.
	Error string `json:"error"`

	// Message Human-readable error detail.
	Message *string `json:"message,omitempty"`
}

// GapDiagnosisResponse defines model for GapDiagnosisResponse.
type GapDiagnosisResponse struct {
	RootCauses []RootCause                `json:"root_causes"`
	Status     GapDiagnosisResponseStatus `json:"status"`
}

// GapDiagnosisResponseStatus defines model for GapDiagnosisResponse.Status.
type GapDiagnosisResponseStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Env Deployment environment.
	Env *string `json:"env,omitempty"`

	// Status Health status of the service.
	Status HealthResponseStatus `json:"status"`

	// Uptime Process uptime (e.g. "1m30s").
	Uptime *string `json:"uptime,omitempty"`

	// Version Build version.
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus Health status of the service.
type HealthResponseStatus string

// JwksResponse defines model for JwksResponse.
type JwksResponse struct {
	// Keys JSON Web Keys (RSA public keys).
	Keys []struct {
		Alg *JwksResponseKeysAlg `json:"alg,omitempty"`

		// E RSA public exponent (base64url).
		E   *string              `json:"e,omitempty"`
		Kid *string              `json:"kid,omitempty"`
		Kty *JwksResponseKeysKty `json:"kty,omitempty"`

		// N RSA modulus (base64url).
		N   *string              `json:"n,omitempty"`
		Use *JwksResponseKeysUse `json:"use,omitempty"`
	} `json:"keys"`
}

// JwksResponseKeysAlg defines model for JwksResponse.Keys.Alg.
type JwksResponseKeysAlg string

// JwksResponseKeysKty defines model for JwksResponse.Keys.Kty.
type JwksResponseKeysKty string

// JwksResponseKeysUse defines model for JwksResponse.Keys.Use.
type JwksResponseKeysUse string

// PlanResponse defines model for PlanResponse.
type PlanResponse struct {
	Checkpoints     *[]Checkpoint `json:"checkpoints,omitempty"`
	GoalModuleId    *string       `json:"goal_module_id,omitempty"`
	LearnerId       string        `json:"learner_id"`
	OntologyVersion *string       `json:"ontology_version,omitempty"`
	PlanId          string        `json:"plan_id"`
	Status          string        `json:"status"`
	Steps           *[]PlanStep   `json:"steps,omitempty"`
	TimelineEnd     time.Time     `json:"timeline_end"`
	TimelineStart   time.Time     `json:"timeline_start"`
}

// PlanStep defines model for PlanStep.
type PlanStep struct {
	Horizon      *string    `json:"horizon,omitempty"`
	ModuleId     string     `json:"module_id"`
	PlannedEnd   *time.Time `json:"planned_end,omitempty"`
	PlannedStart *time.Time `json:"planned_start,omitempty"`
	Position     int        `json:"position"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	// Checks Per-dependency check results.
	Checks *struct {
		Database         *ReadinessResponseChecksDatabase         `json:"database,omitempty"`
		IdentityProvider *ReadinessResponseChecksIdentityProvider `json:"identity_provider,omitempty"`
	} `json:"checks,omitempty"`
	Env *string `json:"env,omitempty"`

	// Status Overall readiness.
	Status  ReadinessResponseStatus `json:"status"`
	Uptime  *string                 `json:"uptime,omitempty"`
	Version *string                 `json:"version,omitempty"`
}

// ReadinessResponseChecksDatabase defines model for ReadinessResponse.Checks.Database.
type ReadinessResponseChecksDatabase string

// ReadinessResponseChecksIdentityProvider defines model for ReadinessResponse.Checks.IdentityProvider.
type ReadinessResponseChecksIdentityProvider string

// ReadinessResponseStatus Overall readiness.
type ReadinessResponseStatus string

// Resource defines model for Resource.
type Resource struct {
	Cost            *float32     `json:"cost,omitempty"`
	Difficulty      *string      `json:"difficulty,omitempty"`
	DurationMinutes *int         `json:"duration_minutes,omitempty"`
	Format          *string      `json:"format,omitempty"`
	Id              string       `json:"id"`
	Source          *string      `json:"source,omitempty"`
	Title           *string      `json:"title,omitempty"`
	Type            ResourceType `json:"type"`
	Uri             *string      `json:"uri,omitempty"`
}

// ResourceType defines model for Resource.Type.
type ResourceType string

// ResourceListResponse defines model for ResourceListResponse.
type ResourceListResponse struct {
	Items []Resource `json:"items"`
	Total int        `json:"total"`
}

// RootCause defines model for RootCause.
type RootCause struct {
	BlockedModules *int     `json:"blocked_modules,omitempty"`
	Mastery        *float32 `json:"mastery,omitempty"`
	ModuleId       string   `json:"module_id"`
}

// RouteComputeRequest defines model for RouteComputeRequest.
type RouteComputeRequest struct {
	// GoalTopicId Goal topic (e.g. "math-5-10").
	GoalTopicId string `json:"goal_topic_id"`

	// LearnerId Learner performing the request.
	LearnerId string `json:"learner_id"`
}

// RouteComputeResponse defines model for RouteComputeResponse.
type RouteComputeResponse struct {
	Metadata *struct {
		ComputedAt  *time.Time `json:"computed_at,omitempty"`
		GoalTopicId *string    `json:"goal_topic_id,omitempty"`
		LearnerId   *string    `json:"learner_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Route Ordered list of topics forming the route.
	Route []RouterTopic `json:"route"`
}

// RouterTopic defines model for RouterTopic.
type RouterTopic struct {
	// LinkType Link type from the parent in the route (e.g. hasStrictPrerequisite).
	LinkType *string `json:"link_type,omitempty"`

	// Order Position in the route (0-based).
	Order   int    `json:"order"`
	TopicId string `json:"topic_id"`
}

// SparqlResponse defines model for SparqlResponse.
type SparqlResponse struct {
	Head struct {
		Vars *[]string `json:"vars,omitempty"`
	} `json:"head"`
	Results struct {
		Bindings *[]map[string]interface{} `json:"bindings,omitempty"`
	} `json:"results"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	// Roles Roles to embed (defaults to ["learner"]).
	Roles *[]string `json:"roles,omitempty"`

	// UserId Subject identifier to embed as the JWT sub claim.
	UserId string `json:"user_id"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken Signed RS256 JWT.
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds (24h).
	ExpiresIn int64                  `json:"expires_in"`
	TokenType TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Roles  []string `json:"roles"`
	UserId string   `json:"user_id"`
}

// DiagnoseGapsParams defines parameters for DiagnoseGaps.
type DiagnoseGapsParams struct {
	LagModuleId string `form:"lag_module_id" json:"lag_module_id"`
}

// GetOntologyConceptParams defines parameters for GetOntologyConcept.
type GetOntologyConceptParams struct {
	// TopicId Concept/topic identifier, e.g. "math-5-1".
	TopicId string `form:"topic_id" json:"topic_id"`
}

// ListResourcesParams defines parameters for ListResources.
type ListResourcesParams struct {
	// Type Resource kind filter.
	Type *ListResourcesParamsType `form:"type,omitempty" json:"type,omitempty"`

	// Format Resource format filter (e.g. video, text, interactive).
	Format *string `form:"format,omitempty" json:"format,omitempty"`

	// Difficulty Difficulty filter (e.g. basic, advanced).
	Difficulty *string `form:"difficulty,omitempty" json:"difficulty,omitempty"`
	Limit      *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListResourcesParamsType defines parameters for ListResources.
type ListResourcesParamsType string

// SparqlQueryParams defines parameters for SparqlQuery.
type SparqlQueryParams struct {
	// Query Read-only SPARQL SELECT query.
	Query string `form:"query" json:"query"`
}

// IssueTokenJSONRequestBody defines body for IssueToken for application/json ContentType.
type IssueTokenJSONRequestBody = TokenRequest

// ComputeRouteJSONRequestBody defines body for ComputeRoute for application/json ContentType.
type ComputeRouteJSONRequestBody = RouteComputeRequest
